spring.application.name=equipsync
basex.host=localhost
basex.port=1984
basex.username=admin
basex.password=1234
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update